version = 1
SPDX-PackageName = "koshinox"
SPDX-PackageSupplier = "Nikita Mitasov <me@ch4og.com>"
SPDX-PackageDownloadLocation = "https://codeberg.org/ch4og/koshinox"

[[annotations]]
path = ["dotfiles/**"]
SPDX-FileCopyrightText = "2025-2026 Nikita Mitasov <me@ch4og.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["assets/screenshot.png"]
SPDX-FileCopyrightText = "2025 Nikita Mitasov <me@ch4og.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["bashame/flake.lock"]
SPDX-FileCopyrightText = "2025-2026 Nikita Mitasov <me@ch4og.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"
