[config]

[templates.waybar]
input_path = './templates/colors.css'
output_path ='~/.config/waybar/generated/colors.css'
post_hook = 'pkill -SIGUSR2 waybar || true'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.gtk3]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.mango]
input_path = './templates/mango.conf'
output_path = '~/.config/mango/conf.d/generated-colors.conf'
post_hook = 'mmsg -d reload_config && sleep 0.1 && mmsg -d reload_config && sleep 0.1 && mmsg -d reload_config && sleep 0.1 && mmsg -d reload_config'

[templates.qt5ct]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kvantum_kvconfig]
input_path = './templates/kvantum.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = './templates/kvantum.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.pywalfox]
input_path = './templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.obs]
input_path = './templates/obs.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'

[templates.fish]
input_path = './templates/fish.fish'
output_path = '~/.config/fish/conf.d/000_colors.fish'

[templates.terminal]
input_path = './templates/terminal.sh'
output_path = '~/.config/term-colors.sh'

[templates.old-terminals]
input_path = './templates/old-terminals.sh'
output_path = '~/.cache/old-terminals.sh'
post_hook = 'sh ~/.cache/old-terminals.sh'
